// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('title_text', {  });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('owner_text', { text: 'Owner' });
    CreateText('group_text', { text: 'Group' });
    CreateText('other_text', { text: 'Other' });
    CreateText('special_text', { text: 'Special' });
    CreateText('read_text', { text: 'Read' });
    CreateText('write_text', { text: 'Write' });
    CreateText('execute_text', { text: 'Execute' });
    CreateText('suid_text', { text: 'SUID' });
    CreateText('sgid_text', { text: 'SGID' });
    CreateText('sticky_text', { text: 'Sticky Bit' });
    CreateGlassButton('clear_button', { onclick: 'clearChmod', text: 'Clear' });
    CreateText('text', { text: '[ 4 ]' });
    CreateText('text1', { text: '[ 2 ]' });
    CreateText('text2', { text: '[ 1 ]' });
    CreateText('text3', { text: '[ 2 ]' });
    CreateText('text4', { text: '[ 4 ]' });
    CreateText('text5', { text: '[ 1 ]' });
    CreateText('text7', { text: 'Octal' });
    CreateText('text8', { text: 'Symbolic' });
    CreateText('text9', { text: 'Syntax Suggestions:' });
    CreateText('text10', { text: 'v0.1' });
    CreateText('mylink', { text: 'www.codeuniversity.com' });
    CreateText('text6', { text: unescape('ChmodPro %u00A9 2010 Steve Dickinson') });
    CreateText('text11', { text: 'ChmodPro' });
    CreateShape('roundedRectangleShape', { rightImageWidth: 5, leftImageWidth: 5 });
    CreateText('text13', { text: 'Hot Keys' });
    CreateText('text14', { text: 'CTRL + i' });
    CreateText('text15', { text: 'Information screen (here)' });
    CreateText('text12', { text: 'ChmodPro' });
    CreateText('text16', { text: 'v0.1' });
    CreateText('text17', { text: 'UNIX/Linux Permissions Professor' });
}
window.addEventListener('load', setupParts, false);
